# Change these first
owner: ocf # Your GitHub organization or username, where this repository lives
repo: ocfuptime # The name of this repository

sites:
  - name: OCF
    url: https://www.ocf.berkeley.edu
  - name: ocf.io
    url: https://ocf.io
  - name: New OCF
    url: https://new.ocf.berkeley.edu
  - name: OCF TheLounge
    url: https://irc.ocf.berkeley.edu
  - name: OCF Chat
    url: https://chat.ocf.berkeley.edu
  - name: OCF Matrix
    url: https://matrix.ocf.berkeley.edu
  - name: OCF Mirrors
    url: https://mirrors.ocf.berkeley.edu
  - name: OCF Mirrors (HTTP)
    url: http://mirrors.ocf.berkeley.edu
  - name: OCF APT Repository
    url: http://apt.ocf.berkeley.edu
  - name: OCF APT Repository (HTTPS)
    url: https://apt.ocf.berkeley.edu
  - name: OCF WebSSH
    url: https://ssh.ocf.berkeley.edu
  - name: OCF HedgeDoc
    url: https://notes.ocf.berkeley.edu
  - name: OCF Auth
    url: https://auth.ocf.berkeley.edu
  - name: OCF Jukebox
    url: https://jukebox.ocf.berkeley.edu
  - name: OCF API
    url: https://api.ocf.berkeley.edu
  - name: OCF Grafana
    url: https://grafana.ocf.berkeley.edu
    expectedStatusCodes:
      - 200
      - 401
  - name: tsunami SSH
    check: "tcp-ping"
    url: ssh.ocf.berkeley.edu
    port: 22
  - name: OCF Mirrors rsync
    check: "tcp-ping"
    url: mirrors.ocf.berkeley.edu
    port: 873
  - name: OCF Jenkins
    url: https://jenkins.ocf.berkeley.edu
  - name: OCF Coder
    url: https://code.ocf.berkeley.edu
  - name: OCF Labmap
    url: https://labmap.ocf.berkeley.edu

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: demo.upptime.js.org
  baseUrl: /ocfuptime
  logoUrl: https://static.ocf.berkeley.edu/img/penguin-swing.svg
  name: OCF Status
  introTitle: "Status of OCF services and systems."
  introMessage: For more information about service interruptions, please also check the [OCF Status Blog](https://status.ocf.berkeley.edu).
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "*/10 * * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/2 * * * *"
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration

commitMessages:
  commitAuthorName: "ocfbot"
  commitAuthorEmail: "officers@ocf.berkeley.edu"
